### ISSUE TITLE
Quizlet

### ISSUE THREAD

**Issue by dacodingguy** [pirate/sites-using-cloudflare#156]
Was quizlet.com affected? I know it uses cloudflare, but I didn't see it on the list. Was it compromised?

**Comment by Zenexer** [comment]
It probably didn't make the original list because it uses branded nameservers.  It should be in the [branded list](https://github.com/pirate/sites-using-cloudflare/issues/141) that we're working on accommodating.  Assuming they haven't just started using Cloudflare in the past few days, then yes, they were affected.
