### ISSUE TITLE
many of the listed domains not affected

### ISSUE THREAD

**Issue by basisbit** [pirate/sites-using-cloudflare#18]
It looks like many of the listed domain don't or didn't use any of the affected cloudflare "features" (for example the reverse proxying) which had to be enabled for a website to possibly be affected. Please bear in mind this repository is referenced and mentioned all over the news now. Please make sure you correctly make assumptions, mark what is an assumption and then filter the list.

**Comment by tycoonlover1359** [comment]
Although I'm not an administrator or contributor of this list, I'm going to take a guess and say that the sites you have described are in this list as a precautionary measure. These sites have likely been found to have somehow been affected by this breach, whether by another site requesting it that did use CloudFlare's services or otherwise. Again, I'm not someone that maintains this, so this is just an assumption on my part.

**Comment by basisbit** [comment]
This is not correct. Apparently, as others pointed out, this seems to be only a list of services which somehow use cloudflare. Seriously, for some of these pages I know for sure that they are not even using any of the affected features.

**Comment by CAD97** [comment]
> I'd rather be safe than sorry so I've included any domain here that remotely touches cloudflare.

**Comment by basisbit** [comment]
@CAD97 in that case the readme.md defintiely needs to be fixed because it states that all listed websites are actually affected. Also, I am wondering what use there is for this list now. You scare lots of customers and lots of it departments now get angry calls from managers because of this list. Thanks a lot.

**Comment by pirate** [comment]
What wording would you propose I use?
I'm open to changing it, but for now I'd rather list everything and remove urls one-by-one as people provide proof that they aren't affected.  The alternative is to only provide URLs that are proven leaked, which means this list will be dangerously out of date until we collect all the data manually.

**Comment by pirate** [comment]
@basisbit I'm aware that this list will cause a lot of angry calls, unfortunately that's the result of a leak like this.  Luckily people who can prove that they aren't affected will be able to sigh in relief and wont have much work to do.

**Comment by basisbit** [comment]
see #17 .

**Comment by basisbit** [comment]
@pirate see #17 .

**Comment by pirate** [comment]
@basisbit #17 is merged, I'm currently changing the wording in the readme to make it very clear that the list is not definitive proof that these sites are compromised.

**Comment by pirate** [comment]
I've added a disclaimer to the README: https://github.com/pirate/sites-using-cloudflare#full-list

**Comment by pirate** [comment]
See: https://github.com/pirate/sites-using-cloudflare/issues/19

**Comment by basisbit** [comment]
usually, you'd mark the newer issues as duplicates and then modify the name of the issue as required. but whatever works best for you :)

**Comment by urc** [comment]
Closing this issue is a bit premature, given that many people are waking up to this, and finding all their domains listed in your file, purely because they are using Cloudflare DNS, without any of the Cloudflare proxy features. It's simply undoable for a hosting service of any reasonable size to request that the domains that shouldn't be on the list be removed from it.

Just the parked domains to begin with, for example. I'm seeing domains in there that have never had an A record since they were originally registered.

**Comment by tycoonlover1359** [comment]
@urc This list contains sites that have **possibly** been affected by this. #29

**Comment by urc** [comment]
@tycoonlover1359 This list contains a ton of sites that are provably not affected my this. Restating the same defense over and over does not change that fact.

**Comment by pirate** [comment]
@urc @basisbit my apologies for closing this issue instead of the newer one.  I'm accepting PRs & Issues to remove unaffected sites, and we've made some significant changes to the README and disclaimer to make it clearer that many of these sites are not affected.  It's a fault of the DNS scraper that we've gotten lots of false positives, but unfortunately there's not an easy way to verify who was using the SSL proxy during that period, so this list is better than nothing in the meantime.
