### ISSUE TITLE
DNS-only customers are included in the list

### ISSUE THREAD

**Issue by DanielMarquard** [pirate/sites-using-cloudflare#43]
Many of my domains, including [critcola.com](https://critcola.com), are included in this list. We use Cloudflare only for DNS, which was never affected by Cloudbleed. All of our traffic is through CloudFront.

I will send a pull request with my domains removed, but this list should really be filtered to remove domains that do not use Cloudflare as a CDN or for front-end caching.

**Comment by tycoonlover1359** [comment]
This is a very...crude...list of sites that use the CloudFlare DNS system. Please note the disclaimer on the README.md (otherwise, the first page you see)
"DISCLAIMER:

This list contains all domains that use cloudflare DNS, not just the cloudflare SSL proxy (the affected service that leaked data). It's a broad sweeping list that includes everything. Just because a domain is on the list does not mean the site is compromised. This list will be narrowed down to the affected domains as I get more information."
#29

**Comment by pirate** [comment]
Yup, we added a disclaimer to the README explaining that this is a DNS list only.

I've confirmed critcola.com isn't using `server:cloudflare-nginx`, go ahead and submit your PR and I'll approve it.
