### ISSUE TITLE
CloudFlare Site Owner Emails

### ISSUE THREAD

**Issue by Teevio** [pirate/sites-using-cloudflare#95]
Our site simplecast.com/fm is on the list of affected sites, but I'm wondering about the legitimacy of the email that CloudFlare sent to customers saying that their site wasn't affected?  We received the email from them saying we were not affected, but it would appear from everything that I've read that this isn't true? Can anyone clarify this for me?

**Comment by caleuanhopkins** [comment]
@Teevio going to try and setup a thread to verify this, see #96

**Comment by coderobe** [comment]
The "your site was not affected" mails seem to be a sort of damage control for CF. I think they sent this to every customer they didn't find cached, leaked info from. If that's true, it's entirely possible for your data to still have leaked, possibly even via completely unrelated sites because of cf proxy node sharing.

**Comment by basisbit** [comment]
I can confirm this. The "your site was not affected" seems to be only related to data for example in Google Cache, but not regarding all the others who stored such data.
